import type { Metadata } from 'next';
import localFont from 'next/font/local';
import ClientProviders from './ClientProviders';

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Glint',
  description: 'Generated by create next app',
};

/**
 * LAYOUT HOME
 * @return {JSX}
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body className={pretendard.className}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
